# Generated by Django 5.2.13 on 2026-07-27 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastereport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['status'], name='waste_waste_status_d5e73a_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['waste_type'], name='waste_waste_waste_t_d0f34e_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['created_at'], name='waste_waste_created_028d52_idx'),
        ),
        migrations.AddIndex(
            model_name='wastereport',
            index=models.Index(fields=['user'], name='waste_waste_user_id_1acabe_idx'),
        ),
    ]
